//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_MindRadar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TISS_MindRadarEntities : DbContext
    {
        public TISS_MindRadarEntities()
            : base("name=TISS_MindRadarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<ConsultantTeams> ConsultantTeams { get; set; }
        public virtual DbSet<Fatigue> Fatigue { get; set; }
        public virtual DbSet<LackOfEnergy> LackOfEnergy { get; set; }
        public virtual DbSet<MentalPhysicalState> MentalPhysicalState { get; set; }
        public virtual DbSet<MentalRelaxation> MentalRelaxation { get; set; }
        public virtual DbSet<MentalState> MentalState { get; set; }
        public virtual DbSet<OverallSelfRegulation> OverallSelfRegulation { get; set; }
        public virtual DbSet<OverallStress> OverallStress { get; set; }
        public virtual DbSet<PersonalAchievement> PersonalAchievement { get; set; }
        public virtual DbSet<PhysicalCondition> PhysicalCondition { get; set; }
        public virtual DbSet<PhysicalDiscomfort> PhysicalDiscomfort { get; set; }
        public virtual DbSet<PhysiologicalRelaxation> PhysiologicalRelaxation { get; set; }
        public virtual DbSet<PsychologicalResponse> PsychologicalResponse { get; set; }
        public virtual DbSet<PsychologicalStateCategory> PsychologicalStateCategory { get; set; }
        public virtual DbSet<PsychologicalStateDescription> PsychologicalStateDescription { get; set; }
        public virtual DbSet<PsychologicalStateHeader> PsychologicalStateHeader { get; set; }
        public virtual DbSet<PsychologicalStateQuestionCategory> PsychologicalStateQuestionCategory { get; set; }
        public virtual DbSet<QuestionCategory> QuestionCategory { get; set; }
        public virtual DbSet<RefereeTeam> RefereeTeam { get; set; }
        public virtual DbSet<SelfEfficacy> SelfEfficacy { get; set; }
        public virtual DbSet<SmoothExperience> SmoothExperience { get; set; }
        public virtual DbSet<SmoothExperienceCategory> SmoothExperienceCategory { get; set; }
        public virtual DbSet<SmoothExperienceResponse> SmoothExperienceResponse { get; set; }
        public virtual DbSet<Successful> Successful { get; set; }
        public virtual DbSet<Team> Team { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<UserResponse> UserResponse { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
