//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_MindRadar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadarCommentLog
    {
        public int LogID { get; set; }
        public string ActionType { get; set; }
        public string TargetType { get; set; }
        public int TargetID { get; set; }
        public int PerformedBy { get; set; }
        public string PerformedRole { get; set; }
        public System.DateTime PerformedAt { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
