//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_MindRadar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadarChartComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RadarChartComment()
        {
            this.RadarChartReply = new HashSet<RadarChartReply>();
        }
    
        public int CommentID { get; set; }
        public int UserID { get; set; }
        public string Role { get; set; }
        public string RadarType { get; set; }
        public System.DateTime SurveyDate { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadarChartReply> RadarChartReply { get; set; }
    }
}
