//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_MindRadar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmoothExperience
    {
        public int QuestionID { get; set; }
        public string QuestionText { get; set; }
        public int ScoreOption1 { get; set; }
        public int ScoreOption2 { get; set; }
        public int ScoreOption3 { get; set; }
        public int ScoreOption4 { get; set; }
        public int ScoreOption5 { get; set; }
        public int CategoryID { get; set; }
    
        public virtual SmoothExperienceCategory SmoothExperienceCategory { get; set; }
    }
}
