//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_MindRadar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string Role { get; set; }
        public string InviteCode { get; set; }
        public bool IsVerified { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Users Users { get; set; }
    }
}
